# Використовуємо офіційний образ OpenJDK 17 (легка версія)
FROM openjdk:17-jdk-slim

# Вказуємо робочу директорію всередині контейнера
WORKDIR /app

# Копіюємо зібраний jar файл у контейнер
# (Припускаємо, що Maven збере його в папку target)
COPY target/radio-0.0.1-SNAPSHOT.jar app.jar

# Відкриваємо порт 8080
EXPOSE 8080

# Команда для запуску програми
ENTRYPOINT ["java", "-jar", "app.jar"]